### ISSUE TITLE
How to access collection helpers?

### ISSUE THREAD

**Issue by MichaelJCole** [fongandrew/meteor-find-and-modify#10]
Hey, this doesn't seem to decorate the return object with it's helpers.  Is there an easy way to do that?

```
TypeError: Object [object Object] has no method 'helperMethod'
```

**Comment by fongandrew** [comment]
I'm not sure what you're referring to. Can you post some example code?

**Comment by MichaelJCole** [comment]
Hey Andrew, thanks for the reply.  I've been debugging all day.

This code works for me:
```
    var affected = Opportunities.update(select, update);
    if (affected) var op = Opportunities.findOne(op._id);
    return op.brand().title;
```

I was hoping to turn that into one write, but I'm getting an error:
```
    op = Opportunities.findAndModify({
      query: select,
      update: update,
      new: true,
    });
    if(op) return op.brand().title;
```

I get this error:  `Exception in setTimeout callback: TypeError: Object [object Object] has no method 'brand'`

I'm thinking that the helper isn't being applied to the object.

Looks like a cool add though.  Any suggestions?

**Comment by fongandrew** [comment]
Oh, it looks like you're using the `transform` option on the Meteor collection.

The `findAndModify` function added here is a thin wrapper around Mongo's `findAndModify`, which means it just returns the raw BSON / EJSON objected stored in Mongo itself. If you want to attach helper functions to that object, you'll need to apply the `transform` function manually.

**Comment by MichaelJCole** [comment]
Ok, sounds easy enough.  Sorry to be dense, but I'm not sure how to do that.

I found this [documentation](http://docs.meteor.com/#/full/mongo_collection)

so I'd wrap the result how to get a Meteor collection item?

```
transform = somefunction?;
op = transform(Opportunities.findAndModify({
      query: select,
      update: update,
      new: true,
    }));
if(op) return op.brand().title;
```

**Comment by MichaelJCole** [comment]
Here's the other code for context:

```
Opportunities = new Mongo.Collection('opportunities');
Schema.Opportunities = new SimpleSchema({
  clientId: {  // Client who initiated opportunity
    type: String,
    regEx: SimpleSchema.RegEx.Id,
    autoValue: Schema.utils.autoMe,
    autoform: { omit: true },
  },
  brandId: {  // The Brand we're working
    type: String,
    regEx: SimpleSchema.RegEx.Id,
    autoform: { omit: true },
  },
});
Opportunities.attachSchema(Schema.Opportunities);

Opportunities.helpers({
  brand: function () {
    return Brands.findOne(this.brandId);
  },
});
```

**Comment by fongandrew** [comment]
Yes, just wrap the result. 

`transform` should be the same `transform` function you used in the definition of the `Opportunities` collection. There is a transform function passed to the constructor, right? If there isn't, then where is the `brand()` helper function defined?

**Comment by fongandrew** [comment]
Oh, huh, you're not using a `transform` function. Attaching helpers to a collection isn't part of Meteor core, so I'm guessing you're using this package (https://github.com/dburles/meteor-collection-helpers)? If so, you should lead with that.

Anyhow, this package currently doesn't support automatically adding helper functions to its return object. You'll have to do that manually via your own transform function, e.g. like so:

```
var transform = function(doc) {
  if (!doc) return;
  doc.brand = function() {
    return Brands.findOne(this.brandId);
  }
}

var opp = transform(Opportunity.findAndModify( ... );
opp.brand();
```

**Comment by fongandrew** [comment]
Alternatively, see if the below works. If a third party package has set a transform on the collection, you may be able to access that transform function directly via `_transform`.

```
Opportunities._transform(Opportunities.findAndModify ( ... ))
```

**Comment by MichaelJCole** [comment]
Worked like a charm!  Thanks 1m!  I've added so many useful packages to Meteor, I forgot what's what :-)

Cheers!
