### ISSUE TITLE
MongoDB 3.2

### ISSUE THREAD

**Issue by valentinvichnal** [fongandrew/meteor-find-and-modify#14]
Hi @fongandrew ,
Nice package, can I use this with MongoDB 3.2+ (which used by Meteor 1.4 as default)?

**Comment by fongandrew** [comment]
The base functionality should still work, although some of the options like `bypassDocumentValidation` and `writeConcern` aren't supported.

**Comment by valentinvichnal** [comment]
Thanks for the reply, it looks to me that it is working but I checked the package and all server side tests are failing, any idea why?

Then I tried to log the tests to see what is happening and the same query ran multiple times when it should run only once, maybe I am missing something because I never used tinytests.

**Comment by babnik63** [comment]
Unfortunatly my server side code stoped after upgrading to meteor 1.4.1 :-(

**Comment by kokokenada** [comment]
I upgraded too and at least there are breaking changes. (findAndModify to an empty table returns an object:  {"lastErrorObject":{"updatedExisting":false,"n":0},"value":null,"ok":1} where as it used to return something falsey...

**Comment by fongandrew** [comment]
OK, I'm not actively developing on Meteor at the moment, so it'll take a while before I can work on this. If someone wants to submit a PR or offer some pointers, that'd be helpful.

**Comment by tcastelli** [comment]
Also confirming it doesn't work with 1.4.1, looking arround to find something that fixes it.

**Comment by tcastelli** [comment]
Okay, have looked into the changes of the new mongodb driver used by 1.4 and saw that the output of findandmodify has changed from previous versions. Now the proper output is in the .value field
https://docs.mongodb.com/manual/reference/command/findAndModify/#output

Will try to change things in local package a send a PR if things continue working.

**Comment by fongandrew** [comment]
Merged #16. Seems to be working for me. Let me know if anyone is still running into issues after updating and I'll re-open.
