### ISSUE TITLE
Getting error on meteor.com hosting after upgrade into 1.1

### ISSUE THREAD

**Issue by chompomonim** [fongandrew/meteor-find-and-modify#5]
After upgrading into 1.1 (from 1.0.3) and `meteor deploy` I'm getting `MongoError: Mod on _id not allowed` on `findAndModify` operations.

On localhost everything works fine.

**Comment by fongandrew** [comment]
Are you doing upserts?

**Comment by chompomonim** [comment]
@fongandrew yes, I was doing upserts.

**Comment by fongandrew** [comment]
It's probably an older version of MongoDB. Upserts only work properly with MongoDB 2.6+ (see https://github.com/fongandrew/meteor-find-and-modify/issues/4 for details). The deployed copy of your app is probably using MongoDB 2.4.x.

I don't know if there's any way to update a deployed MongoDB database on meteor.com yet. If there isn't any important data on your deployed site, I would just delete and re-deploy the site (and hope that it provisions an updated MongoDB the second time around), or deploy to a different name.

**Comment by chompomonim** [comment]
Actually I did deployment on a different name and had same problem.

**Comment by fongandrew** [comment]
Hmm ... Meteor.com is probably still using an older version of MongoDB then.

You can try forcing Meteor to use an older version of this package with `meteor add fongandrew:find-and-modify@=0.1.2`. That should avoid the error you're getting but you'll run into issue #4. Or you can try deploying your Mongo database elsewhere (compose.io supports MongoDB 2.6 and 3.0).

**Comment by fongandrew** [comment]
Closing issue as this should be fixed by MDG. See https://github.com/meteor/meteor/issues/5128.
