### ISSUE TITLE
Getting null return value...

### ISSUE THREAD

**Issue by joetidee** [fongandrew/meteor-find-and-modify#6]
I am using this to try and update a document in my 'Counters' collection:

```
getNextSequence = function () {
    return Counters.findAndModify(
        {
            query: { _id: 'box_id' },
            update: { $inc: { seq: 1 } },
            new: true
        }
    );
};
```

... and I just seem to get null returning - any ideas?

**Comment by fongandrew** [comment]
What version of Meteor and MongoDB are you using?

**Comment by fongandrew** [comment]
Also, I assume this is happening on the server-side?

**Comment by fongandrew** [comment]
A null return value means there was no match. Specifically, nothing matches `query: { _id: 'box_id' }`.

Two possible issues:

* Is `box_id` supposed to be a variable or a fixed string? In the code you copied and pasted above, it's just a string, not a variable.

* Are you trying to do an upsert? If so, you may need to fiddle around with `$setOnInsert`.

**Comment by fongandrew** [comment]
Have you figured this out? If so, I'm going to close the issue.

**Comment by joetidee** [comment]
I have not used this for a while, so up to you if you want to close it.

 

Joe
